[package]
name = "resize"
version = "0.4.3"
authors = ["Kagami Hiiragi <kagami@genshiken.org>", "Kornel <kornel@geekhood.net>"]
description = "Simple image resampling library in pure Rust."
keywords = ["resize", "scale", "resample", "image", "graphics"]
license = "MIT"
readme = "README.md"
categories = ["graphics", "multimedia::images"]
homepage = "https://github.com/PistonDevelopers/resize"
repository = "https://github.com/PistonDevelopers/resize.git"
documentation = "https://docs.rs/resize"
edition = "2018"
include = ["Cargo.toml", "README.md", "LICENSE", "src/*.rs"]

[dev-dependencies]
png = "0.16.7"
